# site settings
title: Pranathi Voora
subtitle: Portfolio
email: pranathivoora2@gmail.com
description: A review of the things I have made<br /> here is my portfolio page
baseurl: "/pranathi-voora-portfolio" # the subpath of your site, e.g. /blog
url: 'https://github.com/vooora/vooora.github.io'
author:
street_address: 1234 Somewhere Road
city: Hyderabad
state: Telangana
zip_code: 
country: India
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/vooora
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/pranathi-voora
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
